name: Publish Traefik image with plugin

on:
  push:
    branches:
      - master

jobs:
  image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          secret_access_key: ${{ secrets.AWS_ACCESS_SECRET }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: public.ecr.aws/oolio/traefik
          region: us-east-1
          dockerfile: Dockerfile
          tags: ${{ github.sha }}
          create_repo: false
